'use client';
import Link from 'next/link';
import {useEffect,useState,useMemo,useRef} from 'react';
import {ArrowUpRight,ArrowRight,ArrowLeft,Search,Pause,Play,BookOpen,ExternalLink,MoveUpRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Slider} from '@/components/ui/slider';
import {events,eras,type Event,type Track} from '@/data/events';
const tracks:Track[]=['Technology','Ideas','Institutions','Governance'];
const camps=[{name:'e/acc',title:'Accelerate the future.',body:'Progress, competition and experimentation are the way forward. Restrictions risk stagnation and concentrating power.',people:'Beff Jezos · Bayeslord · Marc Andreessen',source:'https://beff.substack.com/p/notes-on-eacc-principles-and-tenets'},{name:'Alignment',title:'Make capability controllable.',body:'Build systems whose behavior remains consistent with human intent. Evaluate risks and strengthen oversight as capabilities grow.',people:'AI alignment and safety researchers',source:'https://www.anthropic.com/company'},{name:'Pause',title:'Buy time to get it right.',body:'Pause the most dangerous development until safety and governance catch up. This need not mean stopping all AI research.',people:'Future of Life Institute · pause advocates',source:'https://futureoflife.org/open-letter/pause-giant-ai-experiments/'},{name:'d/acc',title:'Accelerate our defenses.',body:'Favor technologies that support defense, decentralization and democratic resilience while acknowledging AI risks.',people:'Vitalik Buterin',source:'https://vitalik.eth.limo/general/2023/11/27/techno_optimism.html'},{name:'Open models',title:'Distribute the power.',body:'Broader access enables independent research and experimentation. Support for open models is not membership in e/acc.',people:'Open-model community · Meta',source:'https://about.fb.com/news/2024/07/open-source-ai-is-the-path-forward/'},{name:'National strategy',title:'Win the strategic race.',body:'Build domestic AI infrastructure and capabilities while controlling access to strategically sensitive technology.',people:'Governments and national-security institutions',source:'https://www.whitehouse.gov/releases/2025/07/white-house-unveils-americas-ai-action-plan/'}];
export default function Museum(){
 const [era,setEra]=useState(0),[track,setTrack]=useState('All exhibits'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Event|null>(null),[playing,setPlaying]=useState(false),[active,setActive]=useState(0),[camp,setCamp]=useState(0),[about,setAbout]=useState(false),[reduced,setReduced]=useState(false);
 const rail=useRef<HTMLDivElement>(null);
 const visible=useMemo(()=>events.filter(e=>(query?true:e.year>=eras[era].start&&e.year<=eras[era].end)&&(track==='All exhibits'||e.track===track)&&`${e.title} ${e.summary} ${e.people} ${e.date}`.toLowerCase().includes(query.toLowerCase())),[era,track,query]);
 const current=visible[active]??visible[0];
 useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)');setReduced(m.matches);const f=()=>setReduced(m.matches);m.addEventListener('change',f);return()=>m.removeEventListener('change',f)},[]);
 useEffect(()=>{setActive(0);setPlaying(false);rail.current?.scrollTo({left:0,behavior:'instant'})},[era,query,track]);
 useEffect(()=>{if(!playing||!visible.length)return;const t=setInterval(()=>setActive(a=>{if(a>=visible.length-1){setPlaying(false);return a}return a+1}),6500);return()=>clearInterval(t)},[playing,visible.length]);
 useEffect(()=>{const el=rail.current?.children[active] as HTMLElement|undefined;if(el&&rail.current)rail.current.scrollTo({left:el.offsetLeft-rail.current.offsetLeft,behavior:reduced?'instant':'smooth'})},[active,reduced]);
 useEffect(()=>{const onHash=()=>{const e=events.find(x=>`#${x.id}`===location.hash);if(e)setSelected(e)};onHash();addEventListener('hashchange',onHash);return()=>removeEventListener('hashchange',onHash)},[]);
 function open(e:Event){setSelected(e);setPlaying(false);history.replaceState(null,'',`#${e.id}`)}
 function close(){setSelected(null);history.replaceState(null,'',location.pathname+location.search)}
 return <div className={reduced?'museum still':'museum'}>
 <a className="skip" href="#exhibits">Skip to exhibits</a>
 <header><a className="brand" href="#" aria-label="AGI Museum home"><span className="brandmark">a<span>i</span></span><span>AGI<br/>MUSEUM</span></a><nav aria-label="Main navigation"><a href="#exhibits">The timeline</a><a href="#debate">The great debate</a><button onClick={()=>setAbout(true)}>About the archive <ArrowUpRight size={15}/></button></nav><span className="edition">PERMANENT COLLECTION <span>001 / 2026</span></span></header>
 <main>
 <section className="intro"><div className="intro-top"><span className="eyebrow"><span className="live-dot"/> A HISTORY STILL BEING WRITTEN</span><button className="motion-control" onClick={()=>setReduced(!reduced)} aria-pressed={reduced}>{reduced?<Play size={14}/>:<Pause size={14}/>} {reduced?'Motion off':'Motion on'}</button></div><div className="intro-grid"><h1>The making<br/>of <em>intelligence.</em></h1><div className="intro-aside"><span className="large-arrow">↗</span><p>From a question on paper to a world at a threshold. Explore the breakthroughs, the believers, and the battles that brought us here.</p><div className="collection-meta"><span>{events.length} EXHIBITS</span><span>1950 — 2026</span><span>5 GALLERIES</span></div></div></div></section>
 <Link className="expand-timeline" href="/timeline"><img src="/intelligence-gallery.png" alt="" width={1536} height={1024}/><div><span className="eyebrow">THE COLLECTION, UNFOLDED</span><strong>Expand the timeline</strong><p>All 51 exhibits. One continuous journey.</p></div><span className="expand-icon"><ArrowUpRight size={28}/></span></Link>
 <section id="exhibits" className="exhibition"><div className="section-line"><span className="eyebrow">01 / THE TIMELINE</span><span className="small-muted">Select a gallery. Open an exhibit. Follow the evidence.</span></div>
 <Tabs value={String(era)} onValueChange={v=>{setEra(Number(v));setQuery('')}} className="gallery-tabs-root"><TabsList className="era-tabs" aria-label="Timeline galleries">{eras.map((e,i)=><TabsTrigger key={e.title} value={String(i)} className={era===i?'chosen':''}><span className="era-index">0{i+1}</span><div><span>{e.title}</span><small>{e.label}</small></div><ArrowUpRight size={17}/></TabsTrigger>)}</TabsList>
 <div className="gallery-title"><div><p className="eyebrow">GALLERY 0{era+1} <span className="slash">/</span> {eras[era].label}</p><h2>{query?'Search the collection':eras[era].description}</h2></div><div className="gallery-actions"><label className="search"><Search size={17}/><input aria-label="Search all exhibits" placeholder="Search the archive" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}>×</button>}</label></div></div>
 <div className="filter-row"><div className="filters" aria-label="Exhibit categories">{['All exhibits',...tracks].map(t=><button key={t} aria-pressed={track===t} onClick={()=>setTrack(t)} className={track===t?'selected':''}>{t!=='All exhibits'&&<i className={`dot ${t.toLowerCase()}`}/>} {t}</button>)}</div><span className="small-muted" aria-live="polite">{visible.length} exhibits</span></div>
 <TabsContent value={String(era)}>
 {visible.length?<><div className="exhibit-rail" ref={rail} tabIndex={0} aria-label="Exhibit cards; scroll horizontally or use the previous and next controls">{visible.map((e,i)=><button key={e.id} className={`exhibit-card ${i===active?'active':''}`} onClick={()=>open(e)} style={{'--order':i%6} as React.CSSProperties}><div className={`artifact ${e.track.toLowerCase()} ${e.id==='exhibit-01'?'has-photo':''}`}>{e.id==='exhibit-01'&&<img className="turing-image" src="/alan-turing.jpg" alt="Alan Turing as a student, circa 1928–1929" width={675} height={919}/>}<div className="artifact-top"><span>{e.id.replace('exhibit-','OBJECT / ')}</span><span>{e.track.toUpperCase()}</span></div><span className="artifact-year">{e.year}</span><div className="artifact-bottom"><span>{e.track==='Ideas'?'THOUGHT → POSSIBILITY':e.track==='Technology'?'RESEARCH → CAPABILITY':e.track==='Institutions'?'PEOPLE → POWER':'RULES → RESPONSIBILITY'}</span><MoveUpRight size={30}/></div><div className="date-lines" aria-hidden="true">{Array.from({length:21},(_,n)=><i key={n} style={{height:`${10+(n*17)%33}px`}}/>)}</div></div><div className="card-copy"><div className="card-meta"><span><i className={`dot ${e.track.toLowerCase()}`}/>{e.date}</span><span>{e.status==='Forecast / philosophy'?'PERSPECTIVE':e.status==='Company claim'?'REPORTED CLAIM':'ARCHIVE'}</span></div><h3>{e.title}</h3><p>{e.summary}</p><span className="open-label">Explore exhibit <ArrowUpRight size={17}/></span></div></button>)}</div>
 <div className="playback"><div className="tour-control"><button aria-label={playing?'Pause guided tour':'Play guided tour'} onClick={()=>{if(active===visible.length-1)setActive(0);setPlaying(!playing)}}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><span>{playing?'Tour in progress':'Take a guided tour'}<small>{current?.title}</small></span></div><div className="scrubber"><Slider aria-label="Choose exhibit" value={[active]} min={0} max={Math.max(1,visible.length-1)} step={1} disabled={visible.length<2} onValueChange={v=>{setActive(v[0]);setPlaying(false)}}/><span>{String(active+1).padStart(2,'0')} / {String(visible.length).padStart(2,'0')}</span></div><div className="arrows"><button aria-label="Previous exhibit" disabled={!active} onClick={()=>{setActive(a=>a-1);setPlaying(false)}}><ArrowLeft size={20}/></button><button aria-label="Next exhibit" disabled={active>=visible.length-1} onClick={()=>{setActive(a=>a+1);setPlaying(false)}}><ArrowRight size={20}/></button></div></div></>:<div className="empty"><Search size={30}/><h3>No exhibits found.</h3><p>Try another name, year, or idea.</p><button onClick={()=>{setQuery('');setTrack('All exhibits')}}>Reset the archive</button></div>}
 </TabsContent></Tabs></section>
 <section id="debate" className="debate"><div className="section-line"><span className="eyebrow">02 / THE GREAT DEBATE</span><span className="small-muted">Different futures. Shared stakes.</span></div><Tabs value={String(camp)} onValueChange={v=>setCamp(Number(v))} className="debate-grid"><div><p className="eyebrow accent">PROGRESS AT WHAT PACE?</p><h2>One technology.<br/><em>Many futures.</em></h2><p className="debate-intro">The disagreement is about more than speed. It is about control, access, risk—and who gets to decide.</p><TabsList className="camp-tabs" aria-label="Perspectives">{camps.map((c,i)=><TabsTrigger key={c.name} value={String(i)} className={camp===i?'selected':''}>{c.name}{camp===i&&<ArrowUpRight size={16}/>}</TabsTrigger>)}</TabsList></div><TabsContent value={String(camp)} key={camp} className="perspective"><span className="perspective-number">0{camp+1} / 06</span><div className="camp-name">{camps[camp].name}</div><h3>{camps[camp].title}</h3><p>{camps[camp].body}</p><div className="perspective-footer"><span>{camps[camp].people}</span><a href={camps[camp].source} target="_blank" rel="noreferrer">Read the original <ArrowUpRight size={16}/></a></div></TabsContent></Tabs><p className="nuance">These are overlapping perspectives, not fixed teams. Supporting open models does not make someone e/acc; studying safety does not imply opposing progress.</p></section>
 <section className="closing"><span className="eyebrow">THE NEXT EXHIBIT HASN’T HAPPENED YET.</span><h2>History is not<br/>a <em>straight line.</em></h2><p>A benchmark is not a verdict. A forecast is not a fact.<br/>The future remains an open question.</p><button onClick={()=>setAbout(true)}>How to read this collection <BookOpen size={17}/></button></section>
 </main><footer><a className="footer-brand" href="#">AGI MUSEUM <ArrowUpRight size={16}/></a><span>CURATED THROUGH 09 SEPTEMBER 2026</span><span>Sources attached to every exhibit.</span></footer>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)close()}}><DialogContent className="exhibit-dialog">{selected&&<><div className={`detail-year ${selected.track.toLowerCase()}`}>{selected.year}<span>{selected.track}</span></div><div className="detail-body">{selected.id==='exhibit-01'&&<p className="image-credit">Archival portrait: Alan Turing, c. 1928–1929. Turing Digital Archive / <a href="https://commons.wikimedia.org/wiki/File:Alan_Turing_Aged_16.jpg" target="_blank" rel="noreferrer">Wikimedia Commons</a>. Public domain. The photograph predates the 1950 paper.</p>}<p className="eyebrow">{selected.date} · {selected.status}</p><DialogTitle className="detail-title">{selected.title}</DialogTitle><DialogDescription className="detail-summary">{selected.summary}</DialogDescription><h3>Why it belongs here</h3><p>{selected.significance}</p><div className="people"><span className="eyebrow">PEOPLE & INSTITUTIONS</span><p>{selected.people}</p></div><a className="source-link" href={selected.source} target="_blank" rel="noreferrer"><div><span className="eyebrow">FOLLOW THE EVIDENCE</span><strong>{selected.sourceName}</strong></div><ExternalLink size={21}/></a><div className="detail-nav"><button disabled={events.indexOf(selected)===0} onClick={()=>open(events[events.indexOf(selected)-1])}><ArrowLeft size={17}/> Previous</button><span>{selected.id.replace('exhibit-','EXHIBIT ')}</span><button disabled={events.indexOf(selected)===events.length-1} onClick={()=>open(events[events.indexOf(selected)+1])}>Next <ArrowRight size={17}/></button></div></div></>}</DialogContent></Dialog>
 <Dialog open={about} onOpenChange={setAbout}><DialogContent className="about-dialog"><p className="eyebrow">CURATOR’S NOTE</p><DialogTitle className="detail-title">A history still being written.</DialogTitle><DialogDescription>This collection follows the technological, philosophical, institutional and political paths toward AGI through September 9, 2026.</DialogDescription><p>It preserves the major milestones from the researched timeline. It is a selected collection, not a claim to contain every event in AI history. Approximate dates describe periods; exact dates identify documented events.</p><div className="definitions"><p><strong>AGI</strong> Broad intelligence across many domains. There is no universally accepted threshold.</p><p><strong>ASI</strong> Intelligence substantially beyond human capabilities.</p><p><strong>Singularity</strong> A hypothetical transformation driven by rapidly advancing technology.</p></div><p><strong>Read the labels.</strong> Historical events, research findings, forecasts and company claims are distinguished. Sources are linked in every exhibit. Live source pages may be updated after the collection’s cutoff.</p><p>Use gallery tabs, category filters, search, or the guided tour. Exhibit links can be copied from your address bar. Motion can be paused, and your device’s reduced-motion preference is respected.</p></DialogContent></Dialog>
 </div>
}
